=== ysweii/learn_php/XML/demo12.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % p "test">
<!ELEMENT roster ((%p;)+)>
<!ELEMENT %p; (name,sex,birthday,score?,skill+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT birthday (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST %p; id ID #REQUIRED>

=== ysweii/learn_php/XML/test12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE roster SYSTEM "demo12.dtd"[
	<!ENTITY % p "student">
]>
<roster>
	<student id="a1">
		<name>cherry</name>
		<sex>girl</sex>
		<birthday>1991/01/01</birthday>
		<skill>basketball</skill>
	</student>
	<student id="a2">
		<name></name>
		<sex></sex>
		<birthday></birthday>
		<skill></skill>
	</student>
</roster>
